apiVersion: v1
kind: Secret
metadata:
  name: statesvc-secrets
  namespace: default
type: Opaque
stringData:
  database-url: "postgresql://neondb_owner:npg_YIynbl1f3MUc@ep-autumn-king-a4xm63yd-pooler.us-east-1.aws.neon.tech/litellm?sslmode=require"
