apiVersion: v1
kind: Service
metadata:
  name: statesvc-temporal
  namespace: default
  labels:
    app: statesvc-temporal
    component: statesvc
spec:
  type: ClusterIP
  selector:
    app: statesvc-temporal
  ports:
  - name: grpc
    port: 1237
    targetPort: 1237
    protocol: TCP
