apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-temporal
  namespace: default
  labels:
    app: scheduler-temporal
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-temporal
  template:
    metadata:
      labels:
        app: scheduler-temporal
        component: scheduler
    spec:
      hostPID: true
      nodeSelector:
        inferx-gpu-worker: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: scheduler
        image: remodlai/inferx-scheduler:latest
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 1238
          protocol: TCP
        envFrom:
        - configMapRef:
            name: scheduler-config
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: STATESVC_ADDR
          value: "http://statesvc-temporal:1237"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        livenessProbe:
          tcpSocket:
            port: 1238 # temporal port for health check
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 1238
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - mountPath: /opt/inferx/log
          name: opt-inferx-log
      volumes:
      - name: opt-inferx-log
        hostPath:
          path: /opt/inferx/log
