apiVersion: v1
kind: Service
metadata:
  name: scheduler-temporal
  namespace: default
  labels:
    app: scheduler-temporal
    component: scheduler
spec:
  type: ClusterIP
  selector:
    app: scheduler-temporal
  ports:
  - name: grpc
    port: 1238
    targetPort: 1238
    protocol: TCP
